# Generated by Django 3.0.7 on 2020-07-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
