# Generated by Django 3.0.2 on 2020-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='pub_date',
            field=models.DateField(verbose_name='expense date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='../img'),
        ),
    ]
