# Generated by Django 3.0.2 on 2020-03-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200311_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('does_repeat', models.BooleanField(blank=True, verbose_name='Repeats monthly?')),
                ('is_ongoing', models.BooleanField(blank=True, verbose_name='Current?')),
                ('end_date', models.DateField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Category'),
        ),
    ]
