# Generated by Django 3.0.2 on 2020-04-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20200312_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='temp/')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
