# Generated by Django 3.0.2 on 2020-04-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_remove_recurringexpense_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='active',
        ),
    ]
