# Generated by Django 3.0.2 on 2020-04-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_remove_recurringexpense_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
    ]
